### ISSUE TITLE
Not Finding Violations

### ISSUE THREAD

**Issue by lukeb-tph** [packocz/sfdx-code-review-action#8]
@packocz  - I must be missing something, I just don't know what. Each time I run the scan, it always comes back clean. But when I scan it using SFCA directly, violations are found. Not sure why. My simple test is to take a very poorly coded class, format the file, commit, and then run the scan.

```
name: Automated Quality Gate
on:
    workflow_dispatch:
    pull_request:
        types: [labeled]
        branches: [main]
jobs:
    review:
        name: ReviewSource
        runs-on: ubuntu-latest
        if: ${{ github.event.label.name == 'review' }}
        steps:
            - name: Code Review
              uses: pragmatic-bear/sfdx-code-review-action@v0.5.1
              with:
                  pmdconfig: level-1-class-ruleset.xml
                  github_token: ${{ secrets.GITHUB_TOKEN }}
```
